/* ---------------- extra cross-cutting topic ---------------- */
T('feature-vs-experience',{ d:'experience', t:'Experience thinking, not feature thinking', tag:'"We need crafting" is a feature. "Players should make meaningful preparation decisions" is a design goal. Start from the second.',
  what:`Feature thinking starts from a thing to build and justifies it afterwards: feature, implementation, justification. Experience thinking starts from a player behavior and derives the feature last: desired player behavior, experience, system, mechanic, feature. The same word ("crafting") can be the right answer to a behavior goal or a genre reflex. The ladder tells you which.`,
  why:[`Features are how scope inflates: each is plausible, none is necessary, and together they bury the core.`,`A behavior goal admits many solutions, some far cheaper than the feature you first imagined.`,`AI makes features cheap to propose and build; without a behavior goal there is no way to reject them.`],
  think:{ q:[`What do I want the player to do differently? Say it as an observable behavior.`,`What would they feel while doing it?`,`What system creates that situation? What is the smallest mechanic that implements it?`,`Only now: which feature, and could an existing one do the job?`],
    trade:[`Behavior-first design is slower to start and far cheaper to finish.`,`Genre features carry player expectations; omitting one may cost recognition even if it adds no behavior.`],
    traps:[`Writing the behavior to justify the feature you already wanted.`,`Behavior goals that are not observable ("players feel immersed").`,`Skipping the system rung and jumping from behavior to feature.`],
    good:[`Feature proposals arrive with a behavior and a signal attached.`,`Features get cut when a cheaper mechanic produces the behavior.`],
    bad:[`The roadmap is a list of nouns.`] },
  how:[`Use the Behavior Ladder tool: start with the feature idea, climb to the behavior, then descend again to the smallest mechanic.`,`For every feature request, demand the behavior and the observable signal.`,`Compare the original feature with the mechanic the ladder produced. Build the smaller one.`,`Test for the behavior, not for the feature's presence.`],
  ai:{ yes:[`Climb the ladder from a feature to candidate behaviors.`,`Generate alternative mechanics for a stated behavior.`,`Flag feature requests that lack a behavior.`],
       no:[`Choose the behavior. That is what the game is about.`] },
  prompts:[{l:'Ladder climb',p:`Someone proposed the feature "[FEATURE]". Climb the ladder: what player behaviors could this feature exist to produce (list 3, each observable in a playtest)? For the most plausible, what experience does the behavior create? What system would produce that situation? What is the smallest mechanic that implements it? Compare that mechanic with the original feature: which is cheaper and which produces the behavior more reliably?`}],
  verify:[`Are the behaviors observable, or feelings?`,`Did it land back on the original feature by default?`],
  test:[`Did the behavior appear? Measure it directly; do not measure feature usage.`],
  rel:[['core-experience','The behavior serves the core experience.'],['scope-control','The ladder is the scope filter at feature level.'],['should-we-build-this','The decision tree is the ladder plus evidence.'],['hypothesis-driven-design','A behavior goal is a hypothesis.']] });

/* ---------------- AI ROLES ---------------- */
const ROLES = [
  { id:'brainstormer', t:'AI Brainstormer', job:'Expands the possibility space.', use:['You have a well-framed problem and need mechanically distinct options.','You suspect you are anchored on the first idea.','Early in a cycle, before critique.'],
    avoid:['You already have too many options and need a decision.','The fantasy or player is undefined; output will be generic.','You are tempted to ask it to recommend; that is a different role.'],
    starter:`Act as a brainstormer. Given [CONTEXT], generate 8 mechanically distinct solutions to [PROBLEM]. For each: the player decision it creates, the intended emotion, the likely failure mode, implementation complexity, and the evidence that would validate it. Make them genuinely different; reject your own near-duplicates. Do not recommend.`,
    verify:['Are the options distinct in the decision they create, or reskins?','Did it recommend anyway?'] },
  { id:'critic', t:'AI Critic', job:'Attacks assumptions.', use:['After brainstorming, before committing.','A design has consensus and no one has argued against it.','You want to know what would have to be true.'],
    avoid:['After you have committed and cannot change course; it becomes demoralizing noise.','When you actually need to build something to learn more.'],
    starter:`Act as a skeptical critic. Here is a design and the assumptions I know of: [DESIGN]. List every assumption it depends on, including ones I did not state. For each, the player behavior that would disprove it and how likely that behavior is given [PLAYER]. Assume the game feels repetitive after 20 minutes: which decisions are too shallow? Propose the smallest experiments that test your diagnosis.`,
    verify:['Did it find assumptions you did not list?','Are the disproving behaviors observable?'] },
  { id:'systems', t:'AI Systems Designer', job:'Analyzes interactions.', use:['You have several mechanics and need to know how they collide.','Balance questions, economies, dominant strategies.','Before adding a new system: what does it touch?'],
    avoid:['The systems are not yet defined enough to have state; analysis of vapor is fiction.','You want it to decide which emergent behaviors are good.'],
    starter:`Act as a systems designer. Here are our systems with the state each reads and writes: [MAP]. Build the interaction matrix, predict emergent strategies and exploits, simulate [SYSTEM] under three player strategies, and report where decisions collapse. Evaluate for depth per rule, not feature count.`,
    verify:['Are interactions derived from shared state or thematic association?','Does the simulation model real players or optimizers?'] },
  { id:'ux', t:'AI UX Researcher', job:'Finds friction.', use:['You have screenshots, flows or notes to audit.','Onboarding, HUD, menus, readability, accessibility.','Coding silent-test notes into hesitation clusters.'],
    avoid:['Judging whether something feels good; that is observation.','Without the target device and player, its readability claims are guesses.'],
    starter:`Act as a UX researcher. Here is our screen and flow during [MODE] and the decisions the player makes: [DESCRIPTION]. Apply the six questions per element (decision supported, information, when needed, parse speed, cost of missing, world alternative). Apply usability heuristics. Count inputs per frequent task. Report friction ranked by frequency times cost. Do not judge fun.`,
    verify:['Did it know the device and distance?','Did it propose text or pop-ups as fixes?'] },
  { id:'engineer', t:'AI Prototype Engineer', job:'Builds experiments.', use:['You have a hypothesis and need the cheapest build that tests it.','Instrumented prototypes with logging and live tuning.','Simulations, generators, analysis scripts.'],
    avoid:['The hypothesis is not written; the prototype will bundle features.','You are about to keep the prototype as production code without a refactor plan.'],
    starter:`Act as a prototype engineer. Hypothesis: [HYPOTHESIS]. Build the smallest playable test in [ENGINE]: only [MECHANICS], shapes only, no menus or saves. Expose [VALUES] as live sliders; log every input, decision and failure with timestamps; export CSV. Before coding, list the design decisions the code will embed and wait for my choices.`,
    verify:['Did it include anything the hypothesis does not need?','Did it surface embedded decisions?'] },
  { id:'analyst', t:'AI Playtest Analyst', job:'Finds behavioral patterns.', use:['You have notes, transcripts or telemetry from real players.','Coding, clustering, correlating, separating behavior from self-report.'],
    avoid:['Without the hypothesis and your context, it will paraphrase opinions.','Recommending changes in the same pass; keep analysis and design separate.'],
    starter:`Act as a playtest analyst. Hypothesis: [HYPOTHESIS]. Data: [NOTES, TRANSCRIPTS, LOGS]. Code observations as behavior or self-report; cluster behaviors; mark patterns (3 or more players) versus outliers; surface contradictions between doing and saying; align notes to telemetry by time. State what the evidence supports and does not. Do not interpret causes or recommend changes.`,
    verify:['Did it call two testers a pattern?','Did it slide into recommendations?'] },
  { id:'content', t:'AI Content Generator', job:'Creates variations after the system is validated.', use:['The loop is voluntarily replayed and the distinctness criteria are written.','Filling defined niches: enemies that ask a stated question, items that own a stated situation.','Placeholder text and assets for prototypes.'],
    avoid:['Before validation: this is how content spam happens.','Without distinctness criteria: you will get oatmeal.','As a substitute for improving the interaction.'],
    starter:`Act as a content generator under constraints. The system is validated by [EVIDENCE]. Niches to fill, with the situation each owns and the decision it must create: [NICHES]. Generate 3 candidates per niche. For each, state the decision changed, the system touched, and how a player recognizes it as distinct after one use. Reject your own candidates that only change numbers or appearance.`,
    verify:['Did it check for validation evidence or generate regardless?','Are candidates distinct in decision, not in name?'] },
  { id:'project', t:'AI Project Analyst', job:'Finds dependencies, risks and scope problems.', use:['Planning: what must be validated before what.','Risk registers, dependency graphs, full-cost estimates including teaching and balance.','Detecting scope drift and iteration without tests.'],
    avoid:['Ranking risks by importance to the experience; that is judgment.','Estimating market size with false precision.'],
    starter:`Act as a project analyst. Here is our plan, feature list and validation evidence: [DOCS]. Build the dependency graph; flag features scheduled before the results they depend on. Score assumptions by impact if false times uncertainty. Estimate full cost per feature (build, teach, balance, maintain, dilution). Report how many iterations have happened since a player last touched the build.`,
    verify:['Did it include experience risk, not only technical risk?','Did it count build cost only?'] },
  { id:'devil', t:"AI Devil's Advocate", job:'Argues against the current design.', use:['Before any commitment: production, slice, launch.','When the team agrees too easily.','To surface the case for cutting.'],
    avoid:['During a playtest debrief, where evidence should speak first.','As the only voice; it must be paired with the evidence.'],
    starter:`Act as a devil's advocate. Argue as strongly as you can that we should NOT build [FEATURE or DESIGN]: that the player does not want it, that a simpler change to [EXISTING] would produce the behavior, that it dilutes "[CORE EXPERIENCE]", and that its full cost is higher than stated. Then state what evidence would change your mind.`,
    verify:['Did it argue, or hedge?','Is the evidence it asks for observable?'] }
];

/* ---------------- AI FAILURE MODES ---------------- */
const FAILURES = [
  { t:'Generic design', sym:'Output could describe any game in the genre. Nothing surprises.', why:'The prompt lacked fantasy, player, constraints or evidence, so the model returned the genre average.', detect:'Read the proposal with the game name removed. Could it be any game? Ask a colleague to guess which game it is for.', fix:'Re-prompt with the full framework: player, fantasy verbs, what the game is not. Filter every proposal by the fantasy verbs.' },
  { t:'Feature inflation', sym:'The feature list grows every week; core signals do not move.', why:'Proposing and building features is cheap; each is plausible; nobody asked what behavior it produces.', detect:'Count features added versus playtests run. Ratio above one is a warning.', fix:'Require a behavior, a hypothesis and a kill criterion for every feature. Freeze additions until the core loop signal moves.' },
  { t:'Overengineering', sym:'Elaborate systems, abstractions and configurability for problems that do not exist yet.', why:'Models default to completeness and generality; complexity is free to write.', detect:'Ask what would break if the system were half the size. If nothing you have tested, it is too big.', fix:'Specify the smallest version. Ask for the embedded decisions before the build. Throw prototypes away.' },
  { t:'False confidence', sym:'Assertive language, no uncertainty, no sources.', why:'Fluency is the default register. The model does not know what it does not know about your game.', detect:'Ask for assumptions marked given, inferred or invented. Count the invented ones.', fix:'Run the verification pass. Treat every unsupported claim as a hypothesis to test, not a fact.' },
  { t:'Hallucinated best practices', sym:'"Studies show", "industry standard", "players expect", with no checkable source.', why:'Training data is full of confident design advice, much of it folklore.', detect:'Ask for the source. Check it. Ask which named game does this and what happened there.', fix:'Ground claims in your own evidence or in sources you have read. Mark the rest as heuristics.' },
  { t:'Optimizing the wrong metric', sym:'Session count or retention goes up; players describe the game as a chore.', why:'You gave the model a metric; it optimized it. Metrics are proxies; the model does not know what they proxy.', detect:'Ask players why they returned. "Obligation" answers mean the metric is lying.', fix:'Pair every metric with the behavior it stands for and a qualitative check. Ask AI to argue that the metric is wrong.' },
  { t:'Copying genre conventions', sym:'Every system is what the top three games in the genre do.', why:'Convention is the most represented pattern; without a reason to deviate, the model conforms.', detect:'For each convention, ask what behavior it produces in your game. "Players expect it" is not a behavior.', fix:'Use the ladder: behavior first. Ask AI what the convention is for and whether a smaller mechanic would do.' },
  { t:'Excessive complexity', sym:'More rules, exceptions and currencies; longer tutorials; same decisions.', why:'Fixing balance with exceptions is easier than changing the core rule; the model obliges.', detect:'Rule audit: how many rules create no decision?', fix:'Prefer changing a number or a core rule to adding an exception. Cut rules with no decision.' },
  { t:'Premature implementation', sym:'A polished build of an idea nobody has tested.', why:'Building is the model’s strongest skill and the most satisfying output; the hypothesis step got skipped.', detect:'Ask: what question does this build answer? What is the kill criterion? Silence means premature.', fix:'Write the hypothesis. Rebuild as the smallest instrumented prototype. Test before polishing.' },
  { t:'Content spam', sym:'Hundreds of items, enemies or quests that all feel the same.', why:'Generation is cheap; distinctness criteria were never written; the system underneath was not validated.', detect:'Show players pairs. Can they tell them apart by what each makes them do?', fix:'Validate the system first. Write distinctness criteria in terms of decisions. Generate within niches under a human filter.' },
  { t:'Documentation theater', sym:'Beautiful design documents nobody reads; the build does not match them.', why:'Writing documents is easy and looks like progress. Documents are not evidence.', detect:'Compare document length to playtest count. Ask when the document last changed because of a test.', fix:'Replace documents with hypotheses, prototypes and iteration logs. Keep the experience statement and the not-list.' },
  { t:'Analysis paralysis', sym:'Endless comparisons, matrices and tradeoff tables; no decision.', why:'Analysis is cheap and comfortable; deciding is a human act that analysis can postpone indefinitely.', detect:'Count analysis passes since the last decision. More than two is a warning.', fix:'Pick two options. Prototype both in a day. Let players decide. Judgment needs evidence, not more comparison.' },
  { t:'Iteration without player evidence', sym:'Many builds, many changes, no playtests; the design drifts.', why:'AI iteration is fast enough to outrun the testing cadence; each iteration feels like progress.', detect:'When did a player last touch the build? More than two cycles ago is a failure.', fix:'Hard rule: no more than two AI iterations without a player. Schedule tests before builds.' },
  { t:'Treating AI output as authority', sym:'"The AI said" ends design arguments. Nobody remembers deciding.', why:'Fluent, confident output from a tireless source is easy to defer to, especially under time pressure.', detect:'Ask who decided the current design and why. If the answer cites AI output, ownership drifted.', fix:'Use the responsibility matrix. Route embedded decisions to a human by name. Record decisions with the human’s reason.' }
];

/* ---------------- RESPONSIBILITY MATRIX ---------------- */
const MATRIX = [
  ['Define the player and fantasy','PRIMARY','Assist','Identity. AI can draft candidates for you to recognize; it cannot know who you are making this for.'],
  ['Write the core experience statement','PRIMARY','Assist','Authorship. AI can dissect references and propose wordings; the target is yours.'],
  ['Generate alternatives','Assist','PRIMARY','Volume and variety are AI strengths; the human supplies the framing and the filter.'],
  ['Decide game identity and what it is not','PRIMARY','Assist','The not-list is the most human artifact in the project.'],
  ['Analyze complexity vs depth','Shared','Shared','AI audits rules for decisions; humans judge which decisions matter to this player.'],
  ['Find dominant strategies and exploits','Assist','PRIMARY','Simulation and exhaustive reasoning; humans decide which to keep.'],
  ['Build prototypes','Assist','PRIMARY','Speed. Humans write the hypothesis and own the embedded decisions.'],
  ['Judge fun','PRIMARY','Assist','Only observed players show fun; the human interprets. AI can code the observations.'],
  ['Design playtest protocols','Shared','Shared','AI drafts protocols and coding schemes; humans know what the room needs.'],
  ['Run playtests and observe','PRIMARY','Assist','Presence and context. AI can transcribe and log.'],
  ['Analyze playtest data','Shared','PRIMARY','Coding, clustering, correlation are AI strengths; interpretation needs human context.'],
  ['Interpret evidence into meaning','PRIMARY','Assist','What a behavior means for this design depends on intent AI does not hold.'],
  ['Make the final tradeoff','PRIMARY','Assist','AI lays out the tradeoffs; the human chooses which matters most.'],
  ['Generate content variations','Assist','PRIMARY','After validation and with distinctness criteria. Human filters for distinctness.'],
  ['Write implementation code','Assist','PRIMARY','With review and with embedded decisions surfaced.'],
  ['Polish and feel tuning','Shared','Shared','AI implements systems and ranks opportunities; humans judge feel with players.'],
  ['Estimate cost, risk and dependencies','Assist','PRIMARY','Enumeration and graphing; humans rank by importance to the experience.'],
  ['Decide what NOT to build','PRIMARY','Assist','The bottleneck skill. AI can argue for cuts; the human cuts.'],
  ['Decide monetization ethics','PRIMARY','Assist','Values. AI can model revenue and flag friction.'],
  ['Write and maintain the iteration log','Assist','PRIMARY','Bookkeeping; humans write the decisions and reasons.']
];

/* ---------------- MASTER LOOP ---------------- */
const LOOP_STEPS = [
  { n:1, t:'Define', goal:'Player, fantasy, intended experience.', human:'Write the player sketch, the fantasy sentence, the core experience statement, the not-list.', ai:'Draft candidates to react to; dissect reference games; flag contradictions between fantasy and mechanic list.', out:'A one-paragraph experience statement the team can recite.', exit:'Any team member can use the statement to reject an idea.', fail:'Defining in genre terms ("a roguelike deckbuilder") instead of experience terms.', top:['core-experience','fantasy','who-is-the-player'] },
  { n:2, t:'Hypothesize', goal:'What must be true for this game to work?', human:'List the assumptions; rank by impact times uncertainty; write the top ones as testable hypotheses with signals and kill criteria.', ai:'Sharpen vague ideas into hypotheses; propose alternative explanations; enumerate assumptions you did not state.', out:'Three to five hypotheses in the standard form.', exit:'Each hypothesis has an observable signal and a kill criterion.', fail:'Hypotheses about the game instead of about player behavior.', top:['hypothesis-driven-design','risk-and-dependencies'] },
  { n:3, t:'Explore', goal:'Expand the design space.', human:'Frame the problem fully (the formula). Choose which hypothesis to explore.', ai:'Brainstormer: mechanically distinct options with decision, emotion, failure mode, cost and validating evidence for each.', out:'A set of distinct options, none recommended yet.', exit:'Options differ in the decision they create, not just in flavor.', fail:'Generic output from an unframed prompt; asking for a recommendation.', top:['ai-roles','prompting-framework','mechanics-and-rules'] },
  { n:4, t:'Critique', goal:'Attack the assumptions.', human:'Read the critique; decide which attacks are credible for your player.', ai:"Critic and devil's advocate: assumptions per option, disproving behaviors, the case for building none of them.", out:'A shortlist of one or two options with known risks.', exit:'You can state what would make each shortlisted option fail.', fail:'Skipping critique because the team agrees.', top:['verifying-ai-output','ai-failure-modes'] },
  { n:5, t:'Prototype', goal:'Build the cheapest possible test.', human:'Write the prototype brief: hypothesis, minimal mechanics, exposed values, logged events, exclusions.', ai:'Prototype engineer: build it fast with instrumentation; surface embedded decisions first.', out:'A disposable, instrumented build answering one question.', exit:'The build can produce the signal or the kill criterion within a 15-minute session.', fail:'Prototype grows into the game; no logging; polish creeps in.', top:['prototyping','ai-for-implementation'] },
  { n:6, t:'Play', goal:'Observe actual humans.', human:'Recruit matched players; run silent observation; do not explain; take timestamped notes.', ai:'Draft protocols and interview guides; transcribe.', out:'Notes, recordings, logs from real players.', exit:'At least a handful of matched players have played without help.', fail:'Testing with the team; explaining during the test; asking "was it fun?"', top:['playtesting','who-is-the-player'] },
  { n:7, t:'Measure', goal:'Collect behavioral evidence.', human:'Decide which behaviors matter for the hypothesis; log them consistently.', ai:'Code notes; count choices, retries, hesitations, quits; align notes to telemetry.', out:'Behavior data separated from self-report.', exit:'You can state the rate at which the predicted behavior occurred.', fail:'Counting opinions as data; treating two testers as a pattern.', top:['ai-for-playtest-analysis','iteration-and-evidence'] },
  { n:8, t:'Interpret', goal:'Human and AI analyze the evidence.', human:'Add context AI lacks: intent, what changed, what the room felt like. Decide what the evidence means.', ai:'Cluster, find contradictions, propose alternative explanations, surface outliers.', out:'A statement of what the evidence supports and what it does not.', exit:'You can say whether the hypothesis survived, and why, in two sentences.', fail:'Letting the AI summary become the design change list.', top:['ai-for-playtest-analysis','playtesting'] },
  { n:9, t:'Decide', goal:'Keep, change, simplify, or kill.', human:'Make the call. Record the decision, the evidence and the reason. Write the next hypothesis.', ai:'Lay out options and tradeoffs; argue the other side; maintain the log.', out:'A recorded decision and a next hypothesis.', exit:'Someone can read the log and understand why the design is the way it is.', fail:'Drifting into implementation without deciding; deciding on opinion.', top:['iteration-and-evidence','scope-control','should-we-build-this'] },
  { n:10, t:'Implement', goal:'Use AI aggressively for production.', human:'Specify; review; own embedded decisions; keep the scope gate closed to unvalidated features.', ai:'Write production code, tools, content within validated niches; refactor promoted prototypes; write tests.', out:'Production-quality implementation of validated design.', exit:'The implementation matches the validated prototype behavior and the logs still work.', fail:'Implementing unvalidated features because it is cheap.', top:['ai-for-implementation','content-multiplies'] },
  { n:11, t:'Polish', goal:'Amplify the validated experience.', human:'Rank polish by impact on the most important actions; judge feel with players.', ai:'Implement feel systems; rank opportunities by impact per cost; check readability constraints.', out:'Clearer, more satisfying feedback on validated interactions.', exit:'Feedback is clearer, not just louder; readability survives.', fail:'Polishing before validation; uniform juice on everything.', top:['polish-when','game-feel-and-juice'] },
  { n:12, t:'Repeat', goal:'Back to define or hypothesize.', human:'Revisit the experience statement against what players actually enjoyed. Pick the next riskiest assumption.', ai:'Summarize the cycle; propose next hypotheses; detect skipped steps.', out:'An updated experience statement and the next hypothesis.', exit:'The next cycle starts with a hypothesis, not a feature.', fail:'Treating polish as the end.', top:['ai-loop','core-experience'] }
];

/* ---------------- PROMPT TEMPLATES ---------------- */
const PROMPT_TEMPLATES = [
  { id:'brainstorm', cat:'Explore', t:'Brainstorming (distinct options, no recommendation)', vars:['PLAYER','FANTASY','LOOP','PROBLEM','CONSTRAINTS'],
    p:`Act as a brainstormer, not an advisor. Context: player {{PLAYER}}; fantasy {{FANTASY}}; current loop {{LOOP}}. Problem: {{PROBLEM}}. Constraints: {{CONSTRAINTS}}. Generate 8 mechanically distinct solutions. For each: the player decision it creates, the intended emotion, the likely failure mode, implementation complexity (S/M/L), and the observable evidence that would validate or invalidate it. Reject your own near-duplicates before presenting. Do not recommend a solution.` },
  { id:'critique', cat:'Critique', t:'Critique (assumptions and disproving behaviors)', vars:['DESIGN','PLAYER','TIME'],
    p:`Act as a skeptical critic. Design under review: {{DESIGN}}. Target player: {{PLAYER}}. List every assumption the design depends on, including ones I did not state. For each: the player behavior that would disprove it, and how likely that behavior is for this player. Now assume the game feels repetitive after {{TIME}}: identify which underlying decisions are too shallow and propose the smallest experiments that could test your diagnosis. End with the single assumption you would test first and why.` },
  { id:'system-analysis', cat:'Systems', t:'System interaction analysis', vars:['MAP','FANTASY'],
    p:`Act as a systems designer. Systems with the state each reads and writes: {{MAP}}. Produce the pairwise interaction matrix (existing, possible, impossible). For each possible pair, one concrete interaction rule, the emergent strategy it might create, and whether it fits the fantasy "{{FANTASY}}". For each existing pair, the most degenerate strategy it enables. Rank possible interactions by depth added per rule added. Do not add new systems.` },
  { id:'mechanic', cat:'Systems', t:'Mechanic design from a behavior goal', vars:['BEHAVIOR','EXPERIENCE','SYSTEMS','CONSTRAINTS'],
    p:`Desired player behavior: {{BEHAVIOR}}. Desired experience: {{EXPERIENCE}}. Existing systems: {{SYSTEMS}}. Constraints: {{CONSTRAINTS}}. Propose 5 mechanics that would produce the behavior, ordered from smallest to largest. For each: the rule in one sentence, the decision it creates, what it interacts with, teaching cost, and how we would observe the behavior in a 15-minute test. Then argue that an existing system could be changed to produce the behavior without any new mechanic.` },
  { id:'economy', cat:'Systems', t:'Economy design and simulation', vars:['SPEC','HOURS'],
    p:`Economy spec (resources, sources with rates, sinks with costs, converters): {{SPEC}}. Write and run a simulation over {{HOURS}} hours for cautious, average and aggressive spenders. Report balance curves, the hour each resource reaches surplus or starvation, and which spending decisions collapse. Propose the smallest rate or cost changes that keep every resource decision live. State the player-behavior assumptions your simulation makes.` },
  { id:'progression', cat:'Systems', t:'Progression audit', vars:['STEPS','CHURN_TIMES'],
    p:`Progression track with timing: {{STEPS}}. For each step: type (power, horizontal, mastery, unlock, narrative) and the new decision or capability it creates, or "none". Flag steps that make a previous decision dominant. Plot when the player first meets each major system against these churn windows: {{CHURN_TIMES}}. Propose the smallest reordering or merge that puts a capability change in every 30 minutes.` },
  { id:'level', cat:'Level', t:'Level design alternatives (after constraints)', vars:['KNOWN','IDEA','EMOTION','POSITION','CONSTRAINTS'],
    p:`The player currently knows {{KNOWN}}. This level teaches {{IDEA}}. Emotional target: {{EMOTION}}. Pacing position: {{POSITION}}. Constraints: {{CONSTRAINTS}}. Propose 3 six-beat structures (teach, test, twist, combine, master, rest). For each beat: what the player does, what they could fail, what they learn. Make the twists genuinely different. Plot intensity and cognitive load per beat and flag any beat where both peak. Do not describe visuals.` },
  { id:'ux-audit', cat:'UX', t:'UX friction audit', vars:['MODE','ELEMENTS','DECISIONS','DEVICE'],
    p:`Act as a UX researcher. Mode: {{MODE}} on {{DEVICE}}. HUD and screen elements: {{ELEMENTS}}. Decisions the player makes here: {{DECISIONS}}. For each element: decision supported, information carried, when needed, parse speed required, cost of missing it, and whether the world could carry it instead. Flag elements with no decision and elements needed during action that require reading. Count inputs for the 5 most frequent tasks. Propose a minimal HUD.` },
  { id:'narrative', cat:'Narrative', t:'Ludonarrative alignment audit', vars:['SYSTEMS','STORY'],
    p:`Read our mechanics, rewards and punishments as a statement about the world: {{SYSTEMS}}. Compare with our story themes and key scenes: {{STORY}}. List every place mechanics reward what the story condemns or punish what it praises. For each: a mechanic change, a story change, and a way to make the dissonance deliberate and perceived; state which is cheapest. Propose one mechanic that enacts the central theme directly.` },
  { id:'playtest-analysis', cat:'Playtest', t:'Playtest analysis (behavior vs self-report)', vars:['HYPOTHESIS','DATA'],
    p:`Act as a playtest analyst. Hypothesis under test: {{HYPOTHESIS}}. Data (observer notes, transcripts, logs): {{DATA}}. Code every observation as behavior or self-report. Cluster behaviors and report frequency. Mark patterns (3 or more players) versus outliers, and list outliers separately. Surface contradictions between what players did and said. State what the evidence supports about the hypothesis and what it does not. Do not recommend design changes.` },
  { id:'balancing', cat:'Systems', t:'Balancing (niches, not equalization)', vars:['OPTIONS','DATA'],
    p:`Options with rules and numbers: {{OPTIONS}}. Pick and win rate data: {{DATA}}. Identify dominant options and trap options. For each dominant option, the situation that should punish it and a counter or cost that creates that situation. For each trap, the niche it could own or the case for removing it. Do not propose equalizing numbers; propose niches. Predict the pick-rate distribution after your changes.` },
  { id:'scope', cat:'Product', t:'Scope reduction', vars:['FEATURES','EVIDENCE','CORE'],
    p:`Feature list: {{FEATURES}}. Validated evidence so far: {{EVIDENCE}}. Core experience: "{{CORE}}". For each feature: the validated result it depends on, full cost (build, teach, balance, maintain, dilution), and what the player loses without it. Sort into build now, prototype first, defer, cut. Argue against your own build-now list once. Then propose the smallest version of the game that still delivers the core experience.` },
  { id:'prototype', cat:'Build', t:'Instrumented prototype brief', vars:['HYPOTHESIS','ENGINE','MECHANICS','VALUES'],
    p:`Act as a prototype engineer. Hypothesis: {{HYPOTHESIS}}. Build a minimal playable test in {{ENGINE}} containing only {{MECHANICS}}. Shapes only; no menus, saves, progression or audio beyond one feedback tone. Expose {{VALUES}} as live on-screen sliders. Log with timestamps: every input, every decision point with the option chosen, every failure with its cause, session start and end. Export as CSV. Before writing code, list every design decision the code will embed (defaults, structures, numbers) and wait for my choices.` },
  { id:'implement', cat:'Build', t:'Production implementation', vars:['SPEC','CODEBASE','TESTS'],
    p:`Implement {{SPEC}} in our codebase ({{CODEBASE}}). Before coding: restate the spec, list ambiguities, and list the design decisions the implementation will embed; wait for answers. Then implement with tests covering {{TESTS}}. Keep the prototype's logging events intact. After implementing, list what you changed beyond the spec and why, and what you would refactor next.` },
  { id:'refactor', cat:'Build', t:'Refactor a promoted prototype', vars:['CODE','BEHAVIOR'],
    p:`This prototype code is being promoted to production: {{CODE}}. Its validated behavior that must not change: {{BEHAVIOR}}. Propose a refactor plan: what to keep, what to rewrite, what to delete, in what order, with the tests that would prove behavior is preserved at each step. Flag hard-coded values that are actually design decisions and should become data.` },
  { id:'postmortem', cat:'Production', t:'Postmortem', vars:['GOALS','HAPPENED','LOG'],
    p:`Goals at the start: {{GOALS}}. What happened: {{HAPPENED}}. Iteration log: {{LOG}}. Identify: assumptions that turned out false and when we could have known; decisions made on opinion rather than evidence; steps of the loop we skipped; scope added without validation; the moment the project would have changed most if we had playtested. Produce 5 lessons stated as rules we could apply next time, each with the evidence from this project that supports it.` },
  { id:'verify', cat:'Critique', t:'Verification pass on any AI output', vars:[],
    p:`About your previous output: 1. List every assumption and mark each as given by me, inferred, or invented. 2. For each factual or "best practice" claim, give the source or say you have none. 3. What player behavior would prove the proposal wrong? 4. Is this solving the problem I stated, or a nearby one? Quote my problem. 5. Which complexity is necessary and which could be removed? 6. What is the smallest prototype that tests this and what result would kill it? 7. What alternatives did you reject and why? 8. What tradeoff are we making?` }
];

/* ---------------- CHECKLISTS ---------------- */
const CHECKLISTS = [
  { id:'design-review', t:'Design review: any feature', desc:'Run before committing production time to any feature. Every group must have an answer, not a shrug.',
    groups:[
      ['Player',['Who benefits, specifically? Name the player sketch.','What do they feel while using it?','What do they do differently because it exists?']],
      ['Design',['What decision does this create that did not exist before?','What tradeoff does the player face inside it?','What happens if it is removed? Be specific about lost behavior.']],
      ['System',['What does it read and write? What does it interact with?','What strategies emerge from those interactions?','What can break: exploits, runaway loops, dominant options?']],
      ['UX',['Is it understandable by doing, without text?','Is feedback sufficient for success, failure and partial outcomes?','How much does it add to cognitive load during action?']],
      ['Production',['What is the smallest version that tests the idea?','What is the implementation cost, including teaching and balance?','What is the content cost: how many pieces does it need to stay interesting?']],
      ['Evidence',['What assumption are we testing?','How would we observe it in a 15-minute playtest?','What result would make us cut it?']],
      ['AI',['Which part should AI handle: alternatives, prototype, simulation, analysis?','Which part requires human judgment: identity, fun, tradeoff, cut?','What decisions will AI work embed, and who owns them?']] ] },
  { id:'onboarding-audit', t:'Silent onboarding audit', desc:'Watch a new, matched player for ten minutes. No help. No explanation. Check what you observed.',
    groups:[
      ['First 30 seconds',['The player performed the core verb without reading.','The player knew where to go or what to try.','Nothing on screen was asked about.']],
      ['First 5 minutes',['The first meaningful decision happened, and the player hesitated over it.','The first failure happened, and the player could say why.','The player did not skip or ignore a required teaching moment.']],
      ['First session',['A moment of visible competence happened ("I got it").','A reward changed what the player could do, not just a number.','The player can state what they would do next time.','The player used at least two mechanics without prompting.']],
      ['Observer discipline',['I did not speak during play.','I logged every hesitation with a timestamp.','I asked open questions only after play ended.']] ] },
  { id:'ai-verify', t:'AI output verification', desc:'Before acting on any AI design output. If you cannot check a box, do not act on the output yet.',
    groups:[
      ['Assumptions and evidence',['I know which claims came from my context and which were imported or invented.','Every "best practice" or "studies show" has a source I checked, or is marked as a heuristic.','The output uses the evidence I provided; it did not ignore it.']],
      ['Problem fit',['It solves the problem I stated, not a neighboring one.','It respects every constraint I stated.','It did not add complexity that creates no decision.']],
      ['Testability',['There is a smallest prototype that tests it.','There is a kill criterion.','I know what player behavior would prove it wrong.']],
      ['Ownership',['The decisions embedded in the output are surfaced and a human owns them.','I know what alternatives were rejected and why.','I know what tradeoff we are making.']] ] },
  { id:'pre-prototype', t:'Before building a prototype', desc:'A prototype without these is a demo.',
    groups:[
      ['Hypothesis',['Written in the standard form: player, behavior, reason, signal.','A kill criterion exists.','It is about player behavior, not about the game.']],
      ['Scope',['The medium is the cheapest that can answer the question (paper, spreadsheet, grey boxes).','Everything not needed for the question is excluded.','Tuning values are exposed live.']],
      ['Instrumentation',['Inputs, decisions and failures are logged with timestamps.','Logs export in a format I can analyze.','The test protocol fits in 15 minutes per player.']],
      ['Disposal',['I intend to throw this away.','If promoted, a refactor plan will be written first.']] ] },
  { id:'playtest-prep', t:'Playtest session preparation', desc:'Before players arrive.',
    groups:[
      ['Question',['The session has one written question and hypothesis.','I know which behaviors to watch for.','I know what result would surprise me.']],
      ['Players',['Testers match the player sketch.','Testers have not seen this build or been briefed on the design.','Enough testers to distinguish pattern from outlier (at least three).']],
      ['Protocol',['Silent observation first.','Timestamped note template ready.','Open, non-leading interview questions written, ordered from behavior to opinion.']],
      ['After',['Synthesis separates behavior from self-report.','One or two changes chosen, with reasons traceable to evidence.','Iteration log updated.']] ] },
  { id:'scope-sanity', t:'Scope sanity (monthly)', desc:'Cheap implementation makes this the most important review you run.',
    groups:[
      ['Core',['The team can recite the core experience statement.','The not-list exists and was consulted this month.','The core loop signal moved, or we know why not.']],
      ['Features',['Every feature added this month has a hypothesis and a kill criterion.','No feature was built because "AI can do it in a day".','Features count grew slower than playtests count.']],
      ['Content',['Content was added only to validated systems.','Distinctness criteria exist for every content type being generated.','Players can tell recent content pieces apart by what they make them do.']],
      ['Evidence',['A player touched the build within the last two iteration cycles.','Decisions this month cite evidence in the log.','Something was cut this month.']] ] }
];

/* ---------------- SHOULD WE BUILD THIS? ---------------- */
const FEATURE_TREE = [
  { id:'problem', q:'What player problem does it solve?', opts:[['A specific observed problem (from playtests)',3],['A problem we predict but have not observed',1],['No problem; it is an opportunity or a genre expectation',0]] },
  { id:'experience', q:'What experience does it create?', opts:[['A specific emotion or behavior we can name and observe',2],['A general improvement ("more fun", "more depth")',0],['We cannot say',-1]] },
  { id:'decision', q:'What decision does it introduce for the player?', opts:[['A new tradeoff with situational variance',3],['A choice with a probably-dominant option',0],['No decision; it is automatic or cosmetic',-1]] },
  { id:'loop', q:'Does it strengthen the core loop?', opts:[['Directly: it fixes a weak link',3],['Indirectly: it multiplies the loop (content, progression)',1],['It runs beside the loop as a separate activity',-1]] },
  { id:'systems', q:'Does it interact meaningfully with existing systems?', opts:[['Reads and writes shared state with two or more systems',2],['Touches one system',1],['Isolated: its own state, UI and currency',-2]] },
  { id:'simpler', q:'Can the experience be achieved more simply?', opts:[['No; we climbed the ladder and this is the smallest mechanic',2],['Possibly; a change to an existing system might do it',-1],['Yes; we have not tried the simpler change',-3]] },
  { id:'evidence', q:'What evidence suggests players want it?', opts:[['Observed behavior in our playtests (players tried to do this)',3],['Player requests or comparable games',1],['Team intuition only',-1]] },
  { id:'experiment', q:'What is the smallest experiment?', opts:[['A day or less, instrumented, with a kill criterion',2],['A week; needs several systems to exist first',0],['We cannot test it without building it fully',-2]] },
  { id:'without', q:'What happens if we do not build it?', opts:[['A validated player behavior remains impossible',3],['The game is thinner but the core is intact',0],['Nothing observable changes',-3]] }
];
function featureVerdict(score, answers){
  // answers: map id -> option index
  const simplerYes = answers.simpler === 2 || answers.simpler === 1;
  const noEvidence = answers.evidence === 2 || answers.problem === 1 || answers.problem === 2;
  const nothingLost = answers.without === 2;
  const noDecision = answers.decision === 2 && answers.loop === 2;
  if (nothingLost || noDecision || score <= 0) return ['REMOVE','Remove (or never start). The feature creates no decision, or nothing observable is lost without it. Write down why, so the idea does not return next sprint under a new name.'];
  if (simplerYes) return ['SIMPLIFY','Simplify first. A change to an existing system may produce the behavior. Try that in a prototype before building anything new.'];
  if (noEvidence && score < 14) return ['PROTOTYPE','Prototype first. The idea has structure but no player evidence. Write the hypothesis, build the smallest instrumented test, and let players decide.'];
  if (score >= 14 && !noEvidence) return ['BUILD','Build. It solves an observed problem, creates a decision, strengthens the loop, interacts with systems, and we have evidence. Keep the hypothesis and kill criterion anyway.'];
  return ['DEFER','Defer. It depends on things not yet validated or cannot be tested cheaply now. Put it on the list with the evidence that would unlock it.'];
}
