/* =====================================================================
   ENGINES AND TOOLS
   One guide per engine or tool, walking the same eight stages: what it is,
   how it is built, the editor, the content pipeline, building and
   deploying, licensing and cost, working with AI, and interview questions.
   Stages share the platform guides' parts: `points`, dated `facts`, an
   optional `diagram`, `deploy` steps `{t, d, shot?}` drawn as a numbered
   walkthrough, `shots` (each image credited with its licence, see
   IMAGE_LICENCES), and `iv` interview items `{q, a, follow, red}`.
   `glance` is licence and cost, languages, and target platforms.
   Engine tabs inside topics stay Godot and Unity; these guides cover the
   rest of an engine, and say so where it matters.
   ===================================================================== */
const ENGINE_STAGES = [
  ['what', 'What it is and who uses it'], ['architecture', 'How it is built'], ['editor', 'The editor'],
  ['pipeline', 'Content pipeline'], ['deploy', 'Building and deploying'], ['licence', 'Licensing and cost'],
  ['ai', 'Working with AI'], ['interview', 'Interview questions']
];
const ENGINES = [];
/** @param {string} id @param {any} o */
function ENGINE_GUIDE(id, o){ o.id = id; ENGINES.push(o); }

ENGINE_GUIDE('godot', { t:'Godot', kind:'engine', sub:'Free, open-source 2D and 3D engine, 4.x line',
  short:'An MIT-licensed engine with a small editor, text scene files and its own Python-like language. It suits indie teams, 2D games and anyone who wants to own the whole stack.',
  glance:['MIT licence, free, no royalties','GDScript, C# (.NET), C++ via GDExtension','Windows, macOS, Linux, Android, iOS, web; consoles through third parties'],
  stages:{
    what:{ points:['Godot is a general 2D and 3D engine whose editor is itself a Godot application, downloaded as a single executable.','Its 2D is a real 2D pipeline with pixel units, not 3D seen through an orthographic camera.','It suits small teams, 2D and stylised 3D games, and people who want to read or patch the engine source.','Large open-world 3D and console-first projects need more engineering in Godot than in Unreal or Unity.'],
      facts:[{ claim:'The current stable release is Godot 4.7.2, released on 18 August 2026.', asOf:'2026-09-28', src:'https://godotengine.org/download/windows/' }] },
    architecture:{ diagram:{ kind:'stack', title:'Godot, from your script to the GPU', arrow:'calls flow down',
        layers:[{t:'Your code', d:'GDScript, C# or GDExtension classes attached to nodes'},{t:'Scenes and nodes', d:'a tree of nodes, saved and instanced as scenes'},{t:'SceneTree', d:'main loop: process, physics, groups, signals'},{t:'Servers', d:'RenderingServer, PhysicsServer, AudioServer do the work'}] },
      points:['A game is a tree of nodes; a scene is a saved branch of that tree which can be instanced inside other scenes like a prefab.','The SceneTree runs the main loop, calling _process every frame and _physics_process at a fixed physics tick on each node that defines them.','Signals are the observer pattern built in: a node emits a signal and connected callables run, so children never need references to their parents.','Nodes are a convenience layer over servers; RenderingServer and PhysicsServer can be called directly for thousands of objects without node overhead.','GDScript is the built-in, optionally typed scripting language; C# runs on .NET through a separate editor build; GDExtension loads native C++ libraries without recompiling the engine.'] },
    editor:{ points:['The editor switches between 2D, 3D, Script, Game and AssetLib main screens from the top bar.','The Scene dock shows the node tree of the open scene, the FileSystem dock the res:// project folder, and the Inspector the selected node properties.','The built-in script editor has code completion and opens the class reference offline through Search Help.','The active renderer is shown and switched from the top-right corner, and changing it restarts the editor.'],
      shots:[
        { img:'assets/engines/godot-editor.webp', alt:'Godot editor showing a 3D level with the Scene, FileSystem and Inspector docks', caption:'The 3D main screen in a Godot 4.4 build: node tree top left, project files bottom left, properties on the right.', credit:{ author:'Juan Linietsky, Ariel Manzur and the Godot community', url:'https://docs.godotengine.org/en/stable/getting_started/introduction/first_look_at_the_editor.html', licence:'CC BY 3.0' },
          callouts:[{x:0.105,y:0.29,t:'Scene dock: the node tree'},{x:0.10,y:0.68,t:'FileSystem dock: res://'},{x:0.93,y:0.5,t:'Inspector'}] },
        { img:'assets/engines/godot-script.webp', alt:'Godot script editor with a GDScript CharacterBody3D movement script', caption:'The Script screen with a GDScript movement template for CharacterBody3D.', credit:{ author:'Juan Linietsky, Ariel Manzur and the Godot community', url:'https://docs.godotengine.org/en/stable/getting_started/introduction/first_look_at_the_editor.html', licence:'CC BY 3.0' },
          callouts:[{x:0.12,y:0.4,t:'Open scripts'},{x:0.12,y:0.82,t:'Methods in this script'}] }
      ] },
    pipeline:{ points:['Files dropped into the project folder are imported automatically, and import settings live beside each file in a .import sidecar.','glTF 2.0 is the recommended 3D format; imported models become scenes you can inherit from and extend.','Textures get per-file compression settings; audio imports as WAV, Ogg Vorbis or MP3, with WAV suggested for short repeated effects, Ogg Vorbis for music and speech, and MP3 where CPU is tight on mobile and web.','Scenes save as .tscn and resources as .tres, both plain text, so they diff and merge in version control.','Imported data is cached in the .godot folder, which is regenerated and should not be committed.'] },
    deploy:{ points:['Every platform needs export templates matching the exact editor version, downloaded from the editor or built from source.','Export presets per platform are saved in export_presets.cfg, and the command line can export a preset headless for CI.','Consoles are not public: the Godot Foundation ships no console templates, because console SDKs sit under NDA.'],
      deploy:[
        { t:'Install export templates', d:'Download the templates for your exact editor version from Editor, Manage Export Templates.' },
        { t:'Create presets', d:'Add a preset per platform in Project, Export, and set features, icons and included files.' },
        { t:'Desktop builds', d:'Export Windows, macOS and Linux binaries with a packed data file; macOS needs signing and notarisation to open cleanly.' },
        { t:'Android', d:'Install the Android SDK and OpenJDK 17, sign the release with your own keystore, and turn on the Gradle build to export the AAB that Google Play requires.' },
        { t:'iOS', d:'Export an Xcode project from a Mac with your Apple Team ID and bundle identifier, then archive and upload from Xcode.' },
        { t:'Web', d:'Web builds use the Compatibility renderer only; thread support needs cross-origin isolation headers, and C# projects cannot export to web.' },
        { t:'Consoles', d:'Get platform-holder approval, then port through a licensed vendor such as W4 Games under their NDA.' }
      ],
      facts:[
        { claim:'Web export supports only the Compatibility renderer (WebGL 2), and Godot 4 C# projects cannot be exported to the web.', asOf:'2026-09-28', src:'https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html' },
        { claim:'Threaded web builds need SharedArrayBuffer, which needs the Cross-Origin-Opener-Policy: same-origin and Cross-Origin-Embedder-Policy: require-corp headers, or the PWA service-worker workaround.', asOf:'2026-09-28', src:'https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html' },
        { claim:'iOS export must be done on macOS with Xcode installed, using an Apple developer Team ID and a unique bundle identifier.', asOf:'2026-09-28', src:'https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_ios.html' },
        { claim:'The Godot Foundation maintains no official console ports; W4 Games offers Switch, Xbox Series and PlayStation 5 ports, and vendors such as RAWRLAB, Lone Wolf Technology and Pineapple Works also port.', asOf:'2026-09-28', src:'https://godotengine.org/consoles/' }
      ] },
    licence:{ points:['Godot is MIT-licensed: no royalties, no revenue threshold, no seat fees and no splash screen requirement.','You must include the Godot copyright and licence notice with your game, for example in the credits.','Your game content is yours; the engine licence does not cover your own assets or code.','The non-profit Godot Foundation stewards the project, and an MIT release you already use cannot be relicensed out from under you.'],
      facts:[{ claim:'Godot is released under the MIT (Expat) licence, owes no royalties, and asks games to include its copyright and licence notice; the Godot Foundation hosts the project.', asOf:'2026-09-28', src:'https://godotengine.org/license/' },
        { claim:'The renderers are Forward+ (Vulkan, Direct3D 12 or Metal, desktop), Mobile (same APIs, mobile and desktop) and Compatibility (OpenGL, low-end devices and the web).', asOf:'2026-09-28', src:'https://docs.godotengine.org/en/stable/tutorials/rendering/renderers.html' }] },
    ai:{ points:['Scenes and resources are text (.tscn, .tres, project.godot), so an agent can read, diff and edit them, though hand-editing resource ids is fragile.','The class reference is complete and versioned, and the engine source is public, so an agent can check any API against the real code.','Godot 4 renamed much of the Godot 3 API (KinematicBody to CharacterBody, yield to await, new signal syntax), and models trained on old tutorials still write Godot 3 code.','The editor runs headless from the command line, so an agent can run scripts, imports, tests and exports in CI with --headless.','Laying out scenes, tuning in the inspector, animation curves and judging how the game feels stay editor work an agent cannot see.'] },
    interview:{ iv:[
      { q:'What is the difference between a node and a scene in Godot?', a:'A node is one object with one job, such as a sprite or a collision shape. A scene is a saved tree of nodes that can be instanced many times and nested inside other scenes, which is how Godot does prefabs and composition.', follow:'How would you share behaviour between two different enemy scenes?', red:'Saying they are the same thing, or inheriting classes for everything; it shows no feel for composition by scenes.' },
      { q:'When do you use signals instead of direct method calls?', a:'Signals go up and across the tree: a child emits, and whoever cares connects, so the child never knows its parent. Direct calls go down to children you own. That keeps scenes reusable in isolation.', follow:'How do you avoid a dangling connection when a node is freed?', red:'Using get_parent() chains everywhere; scenes then break as soon as they move in the tree.' },
      { q:'What is the difference between _process and _physics_process?', a:'_process runs once per rendered frame with a variable delta. _physics_process runs at the fixed physics tick, so movement and collision code belongs there to behave the same at any frame rate.', follow:'How would you smooth a physics-driven object on a 144 Hz display?', red:'Putting movement in _process without delta; speed then depends on frame rate.' },
      { q:'Why might you choose GDScript over C#, or the reverse?', a:'GDScript is tightly integrated, reloads fast and exports everywhere, including the web. C# gives static typing, .NET libraries and faster heavy logic, but needs the .NET editor build and cannot export to the web in Godot 4.', follow:'Where would GDExtension fit instead?', red:'Claiming C# is always better; it ignores the web limitation and the integration cost.' },
      { q:'A Godot web build hangs on a blank screen on itch.io. What do you check?', a:'Whether it was exported with threads, which are off by default since Godot 4.3, because a threaded build needs cross-origin isolation headers for SharedArrayBuffer. I would enable the host setting that sends them, use the PWA workaround, or export without threads. Then I read the browser console for errors.', follow:'What does exporting without threads cost you?', red:'Blaming the browser and re-uploading; it shows no knowledge of COOP and COEP.' },
      { q:'How would you ship a Godot game on consoles?', a:'Godot has no public console templates because the SDKs are under NDA. You get approved by the platform holder, then work with a porting vendor such as W4 Games, and budget for certification like any other engine.', follow:'What in your codebase makes a port harder?', red:'Saying you just pick a console in the export dialog.' }
    ] }
  },
  flow:{ kind:'flow', title:'godot: from project to a shipped build',
    steps:[{id:'proj', t:'Create project', d:'pick a renderer'},{id:'scenes', t:'Build scenes', d:'nodes, scripts, signals'},{id:'import', t:'Import assets', d:'glTF, textures, audio'},{id:'tpl', t:'Install templates', d:'exact editor version'},{id:'preset', t:'Export presets', d:'one per platform'},{id:'sign', t:'Sign builds', d:'keystore, Apple team, notarise'},{id:'ship', t:'Upload to stores', d:'Steam, Play, App Store, web'}],
    edges:[['proj','scenes'],['scenes','import'],['import','tpl'],['tpl','preset'],['preset','sign'],['sign','ship']] },
  topics:['platform-choice','quality-and-build-health','prototyping','ai-for-implementation']
});

ENGINE_GUIDE('unity', { t:'Unity', kind:'engine', sub:'Commercial 2D and 3D engine, Unity 6 line',
  short:'A proprietary engine with C# scripting, a huge asset and plugin ecosystem and very wide platform reach. It suits mobile studios, mid-size 3D teams and anyone who needs consoles and XR from one codebase.',
  glance:['Personal free under $200,000; Pro per seat above','C# on Mono or IL2CPP; C++ native plugins','Windows, macOS, Linux, Android, iOS, web, XR; consoles with approval'],
  stages:{
    what:{ points:['Unity is a component-based 2D and 3D engine with a closed-source runtime and editor, scripted in C#.','Its strengths are mobile, cross-platform reach and the Asset Store, which sells ready tools, shaders and art.','Unity 6 ships as yearly LTS releases with production-ready Update releases in between, numbered 6000.x.','It suits teams shipping on phones, XR headsets and consoles from one project, less so a team wanting to own the engine source.'],
      facts:[{ claim:'Unity 6.6 (6000.6) was released on 1 September 2026 as a Supported release, the last before Unity 6.7 LTS.', asOf:'2026-09-28', src:'https://discussions.unity.com/t/unity-6-6-is-now-available/1735357' },
        { claim:'Unity 6.3 is the latest LTS, supported until December 2027; Unity 6.0 LTS is supported through October 2026; LTS releases get two years, plus one more for Enterprise and Industry.', asOf:'2026-09-28', src:'https://unity.com/releases/unity-6/support' }] },
    architecture:{ diagram:{ kind:'stack', title:'Unity, from your script to the GPU', arrow:'calls flow down',
        layers:[{t:'Your code', d:'C# MonoBehaviours, ScriptableObjects or ECS systems'},{t:'GameObjects and components', d:'scenes and prefabs hold GameObjects with components'},{t:'Player loop', d:'Awake, Start, FixedUpdate, Update, LateUpdate'},{t:'Native engine', d:'C++ runtime, render pipeline (URP or HDRP), physics, audio'}] },
      points:['A scene holds GameObjects, each an empty container whose behaviour comes entirely from attached components such as Transform, Rigidbody and your scripts.','A MonoBehaviour gets lifecycle callbacks: Awake and OnEnable on load, Start before its first frame, FixedUpdate at the physics step, Update each frame, LateUpdate after all Updates, OnDestroy at teardown.','Prefabs are saved GameObject hierarchies with nesting and variants; ScriptableObjects are data assets shared by reference instead of copied per object.','C# runs on Mono with JIT compilation in the editor and some players, or on IL2CPP, which converts IL to C++ and compiles it ahead of time.','Rendering goes through a Scriptable Render Pipeline: URP for mobile to desktop, HDRP for high-end PC and consoles; the Built-In pipeline is deprecated.','DOTS is an optional data-oriented stack of Entities (ECS), the Burst compiler and the Job System, used for tens of thousands of objects rather than as the default.'] },
    editor:{ points:['The default layout has the Hierarchy of the open scene, the Project window of Assets, the Inspector and the Scene and Game views.','Play mode runs the game inside the editor, and changes made in Play mode are lost when you stop unless you copy them out.','Unity 6.6 makes Fast Enter Play Mode, which skips the domain reload, the default for new projects, so static state can survive between runs.','The Package Manager installs engine features such as URP, Input System, Addressables and Entities as versioned packages listed in Packages/manifest.json.','No editor screenshots ship with this guide, because no Unity image under a verified free licence or official press kit was found.'] },
    pipeline:{ points:['The Asset Database imports every file under Assets into a cached engine format in the Library folder, which is regenerated and never committed.','Each asset has a .meta file holding its GUID and import settings; scenes reference assets by GUID, so meta files are committed and moved with their assets.','Asset Serialization set to Force Text, the default, saves scenes, prefabs and assets as YAML that diffs in version control, though merges need care or Unity Smart Merge.','Addressables loads content by address from local or remote bundles, so builds stay small and content updates can ship without a new store build.','Per-file import settings for textures, models and audio, such as compression and max size, usually decide build size more than code does.'],
      facts:[{ claim:'A .meta file holds the asset unique ID and all its import settings; moving an asset outside Unity without its .meta breaks references.', asOf:'2026-09-28', src:'https://docs.unity3d.com/6000.6/Documentation/Manual/AssetMetadata.html' },
        { claim:'Asset Serialization Mode offers Mixed, Force Binary and Force Text, and Force Text is the default.', asOf:'2026-09-28', src:'https://docs.unity3d.com/6000.6/Documentation/Manual/class-EditorManager.html' }] },
    deploy:{ points:['Builds are configured in File, Build Profiles, which saves several independent configurations per platform, and batch mode can build them for CI.','IL2CPP is required on AOT platforms such as iOS, web and most consoles, and is the usual choice for Android release builds.','Consoles are closed: they need a Pro plan or a Preferred Platform licence key from the platform holder, and developer approval from Sony, Microsoft or Nintendo before you get the console build modules.'],
      deploy:[
        { t:'Install modules', d:'Add platform build support modules for your exact editor version in Unity Hub.' },
        { t:'Create build profiles', d:'Open File, Build Profiles, add a profile per platform, and set scenes, scripting defines and player settings overrides.' },
        { t:'Choose scripting backend', d:'Pick IL2CPP in Player settings for release builds, set code stripping, and test that reflection-heavy code survives it.' },
        { t:'Desktop builds', d:'Build Windows, macOS and Linux players; macOS builds need signing and notarisation to open without warnings.' },
        { t:'Android', d:'Target ARM64 with IL2CPP, sign with your own keystore in Publishing Settings, and build an AAB for Google Play.' },
        { t:'iOS', d:'Build an Xcode project, open it on a Mac with your Apple team and bundle identifier, then archive and upload.' },
        { t:'Web', d:'Web builds run as WebAssembly through IL2CPP, and the host must serve the compressed build files with matching headers.' },
        { t:'Consoles', d:'Get platform-holder approval, install the console build modules through each holder’s developer programme, and pass their certification.' }
      ],
      facts:[{ claim:'IL2CPP is an ahead-of-time pipeline that converts C# IL to C++ and compiles it to native code, and is required on several platforms where JIT is not available.', asOf:'2026-09-28', src:'https://docs.unity3d.com/6000.6/Documentation/Manual/scripting-backends.html' },
        { claim:'Build Profiles, opened from File, Build Profiles, save multiple independent build configurations per platform.', asOf:'2026-09-28', src:'https://docs.unity3d.com/6000.6/Documentation/Manual/build-profiles.html' },
        { claim:'Building for PlayStation, Xbox and Nintendo platforms needs an active Unity Pro subscription or a Preferred Platform licence key from the platform holder, plus developer approval from each platform holder.', asOf:'2026-09-28', src:'https://unity.com/solutions/console' },
        { claim:'The Built-In Render Pipeline is deprecated and will be made obsolete in a future release; it is supported through the Unity 6.7 LTS lifecycle.', asOf:'2026-09-28', src:'https://docs.unity3d.com/6000.6/Documentation/Manual/render-pipelines.html' }] },
    licence:{ points:['Unity is proprietary and licensed per seat; your plan is set by the revenue and funding of your company over the last 12 months.','Unity Personal is free under $200,000 of revenue and funding, and the Made with Unity splash screen is optional in Unity 6.','Unity Pro is required above $200,000 and Enterprise above $25 million, and both rose in price in 2025 and again in 2026.','In September 2023 Unity announced a per-install Runtime Fee, revised it ten days later after a developer backlash, and cancelled it in September 2024.','The lesson: a vendor engine can change its terms mid-project, so read the terms for the version you pin, review them before upgrading, and keep an exit estimate.'],
      facts:[{ claim:'Personal is free up to $200,000 revenue and funding; Pro is $2,310 per seat per year or $210 per month, required above $200,000; Enterprise is required above $25 million with custom pricing.', asOf:'2026-09-28', src:'https://unity.com/products/pricing-updates' },
        { claim:'On 12 September 2024 CEO Matt Bromberg cancelled the Runtime Fee for games, effective immediately, and raised Pro by 8% and Enterprise by 25% from 1 January 2025.', asOf:'2026-09-28', src:'https://unity.com/blog/unity-is-canceling-the-runtime-fee' },
        { claim:'The per-install fee announced in September 2023 was due from 1 January 2024; the 22 September 2023 open letter exempted Personal, limited it to the next LTS shipping in 2024 onward, exempted games under $1 million in revenue, and let studios pay the lesser of 2.5% of revenue or the install-based fee.', asOf:'2026-09-28', src:'https://unity.com/blog/an-open-letter-to-our-community' }] },
    ai:{ points:['With Force Text, scenes and prefabs are YAML an agent can read, but they reference assets by GUID and fileID, so hand edits easily break links.','C# and the scripting API are heavily documented and well represented in training data, so agents write MonoBehaviour code fluently.','Training data mixes eras: the old Input Manager versus the Input System, Built-In versus URP shaders, and pre-6 APIs, so check code against the versioned docs.','The editor runs headless with -batchmode, -executeMethod and -runTests, so an agent can run builds and tests from CI without the GUI.','Wiring references in the Inspector, lighting, animation and feel stay editor work an agent cannot see or verify.'] },
    interview:{ iv:[
      { q:'What is the order of Awake, OnEnable, Start and Update, and why does it matter?', a:'Awake runs when the object loads, then OnEnable, then Start just before its first Update, then Update every frame. Initialise your own state in Awake and read other objects in Start, because Awake order between objects is not guaranteed.', follow:'How would you force one script to run before another?', red:'Doing cross-object lookups in Awake; it works by luck until load order changes.' },
      { q:'When do you pick IL2CPP over Mono?', a:'IL2CPP is mandatory on iOS, web and most consoles and is the norm for Android release builds, giving native AOT code. Mono builds faster, so it suits iteration. IL2CPP stripping can remove code used only through reflection, so you add link.xml or Preserve attributes.', follow:'How would you debug a crash that only happens in IL2CPP builds?', red:'Saying there is no difference; it ignores AOT limits and code stripping.' },
      { q:'Why do .meta files matter in version control?', a:'They hold each asset GUID and import settings, and every reference in scenes and prefabs points to that GUID. Losing or regenerating a meta file breaks those links, so meta files are committed and moved with their assets.', follow:'How do you handle merge conflicts in scene YAML?', red:'Putting meta files in .gitignore; the team then gets missing references on every pull.' },
      { q:'URP or HDRP for a new project?', a:'URP for anything that ships on mobile, Switch or web, or wants one pipeline across platforms. HDRP only for high-end PC and current consoles where the visual target needs it. The Built-In pipeline is deprecated, so I would not start new work on it.', follow:'What breaks when you migrate an old project to URP?', red:'Picking HDRP for a mobile game because it looks better.' },
      { q:'What did the 2023 Runtime Fee teach studios?', a:'Unity announced a per-install fee, revised it within ten days and cancelled it a year later. An engine licence is a dependency with risk, so studios read the terms for the version they pin, track changes and keep an estimate of what a port would cost.', follow:'How would that change your engine choice for a new project?', red:'Saying it no longer matters because it was cancelled; the terms can still change.' },
      { q:'When would you use DOTS instead of GameObjects?', a:'When you simulate tens of thousands of similar entities, such as crowds or projectiles, and GameObject overhead shows in the profiler. Otherwise GameObjects are simpler and better supported by tools, and the two can be mixed.', follow:'What does the Burst compiler add?', red:'Rewriting a whole small game in ECS for speed with no profiling.' }
    ] }
  },
  flow:{ kind:'flow', title:'unity: from project to a shipped build',
    steps:[{id:'proj', t:'Create project', d:'URP or HDRP template'},{id:'scenes', t:'Build scenes', d:'GameObjects, prefabs, C#'},{id:'assets', t:'Import assets', d:'meta files, Force Text'},{id:'addr', t:'Addressables', d:'group remote content'},{id:'profile', t:'Build profiles', d:'one per platform'},{id:'il2cpp', t:'IL2CPP build', d:'strip and test'},{id:'sign', t:'Sign builds', d:'keystore, Apple team, notarise'},{id:'ship', t:'Upload to stores', d:'Steam, Play, App Store, consoles'}],
    edges:[['proj','scenes'],['scenes','assets'],['assets','addr'],['addr','profile'],['profile','il2cpp'],['il2cpp','sign'],['sign','ship']] },
  topics:['platform-choice','business-model','quality-and-build-health','ai-for-implementation','pm-risk']
});
